export const productData = [
  {
    category: "sarees",
    collections: [
      {
        slug: "cotton-saree-collection",
        heading: "Cotton Sarees",
        collectionType: "cotton",
        type: "sarees",
        images: ["/productImages/cottonSaree.webp"],
        products: [
          {
            title: "Handwoven Cotton Saree",
            images: [
              "/productImages/cottonSaree1.jpg",
              "/productImages/cottonSaree1-2.jpg",
            ],
            slug: "handwoven-cotton-saree",
            price: 1500,
            quantity: 20,
            description:
              "A lightweight and breathable handwoven cotton saree, perfect for daily wear.",
            material: "100% Cotton",
            washCare: "Hand wash separately in cold water.",
            rating: 4.5,
            date_added: "2024-01-01",
            type: "sarees",
            collectionType: "cotton",
          },
          {
            title: "Printed Cotton Saree",
            images: [
              "/productImages/cottonSaree2.webp",
              "/productImages/cottonSaree2-2.webp",
            ],
            slug: "printed-cotton-saree",
            price: 1800,
            quantity: 15,
            description:
              "A beautifully printed cotton saree with intricate patterns.",
            material: "100% Cotton",
            washCare: "Machine wash in gentle cycle with mild detergent.",
            rating: 4.4,
            date_added: "2024-01-01",
            type: "sarees",
            collectionType: "cotton",
          },
        ],
      },
      {
        slug: "silk-saree-collection",
        heading: "Silk Sarees",
        collectionType: "silk",
        type: "sarees",
        images: ["/productImages/silkSaree1.webp"],
        products: [
          {
            title: "Banarasi Silk Saree",
            images: [
              "/productImages/silkSaree1.webp",
              "/productImages/silkSaree1-1.webp",
            ],
            slug: "banarasi-silk-saree",
            price: 5000,
            quantity: 10,
            description:
              "A luxurious Banarasi silk saree with intricate zari work.",
            material: "Pure Silk",
            washCare: "Dry clean only.",
            rating: 5,
            date_added: "2024-01-01",
            type: "sarees",
            collectionType: "silk",
          },
          {
            title: "Kanchipuram Silk Saree",
            images: [
              "/productImages/silkSaree2.webp",
              "/productImages/silkSaree2-2.webp",
            ],
            slug: "kanchipuram-silk-saree",
            price: 7000,
            quantity: 8,
            description:
              "An exquisite Kanchipuram silk saree with traditional motifs.",
            material: "Pure Silk",
            washCare: "Dry clean only.",
            rating: 4.2,
            date_added: "2024-01-02",
            type: "sarees",
            collectionType: "silk",
          },
        ],
      },
      {
        slug: "banarasi-saree-collection",
        heading: "Banarasi Sarees",
        collectionType: "banarasi",
        type: "sarees",
        images: ["/productImages/banarasiSaree1.webp"],
        products: [
          {
            title: "Red Banarasi Saree",
            images: [
              "/productImages/banarasiSaree1.webp",
              "/productImages/banarasiSaree1-2.webp",
            ],
            slug: "red-banarasi-saree",
            price: 6000,
            quantity: 12,
            description:
              "A stunning red Banarasi saree with golden zari embroidery.",
            material: "Silk Blend",
            washCare: "Dry clean only.",
            rating: 4.8,
            date_added: "2024-01-03",
            type: "sarees",
            collectionType: "banarasi",
          },
        ],
      },
      {
        slug: "georgett-saree-collection",
        heading: "Georgett Sarees",
        collectionType: "georgett",
        type: "sarees",
        images: ["/productImages/georgetteSaree1.webp"],
        products: [
          {
            title: "Georgett Saree",
            images: [
              "/productImages/georgetteSaree1.webp",
              "/productImages/georgetteSaree1-1.webp",
            ],
            slug: "georgett-saree",
            price: 3000,
            quantity: 10,
            description: "A beautiful georgett saree with intricate patterns.",
            material: "Georgett",
            washCare: "Dry clean only.",
            rating: 4.9,
            date_added: "2024-01-04",
            type: "sarees",
            collectionType: "georgett",
          },
        ],
      },
    ],
  },
  {
    category: "suits",
    collections: [
      {
        slug: "cotton-suit-collection",
        heading: "Cotton Suits",
        collectionType: "cotton",
        type: "suits",
        images: ["/productImages/cottonSuit1.jpg"],
        products: [
          {
            title: "Printed Cotton Suit",
            images: [
              "/productImages/cottonSuit1.webp",
              "/productImages/cottonSuit1-2.webp",
            ],
            slug: "printed-cotton-suit",
            price: 2500,
            quantity: 18,
            description: "A comfortable cotton suit set with vibrant prints.",
            material: "100% Cotton",
            washCare: "Machine wash in cold water with similar colors.",
            rating: 3.1,
            date_added: "2024-01-05",
            type: "suits",
            collectionType: "cotton",
          },
        ],
      },
      {
        slug: "silk-suit-collection",
        heading: "Silk Suits",
        collectionType: "silk",
        type: "suits",
        images: ["/productImages/silkSuit1.jpg"],
        products: [
          {
            title: "Embroidered Silk Suit",
            images: [
              "/productImages/silkSuit1.webp",
              "/productImages/silkSuit1-2.webp",
            ],
            slug: "embroidered-silk-suit",
            price: 4500,
            quantity: 10,
            description:
              "An elegant silk suit set with hand-embroidered details.",
            material: "Silk Blend",
            washCare: "Dry clean only.",
            rating: 3.2,
            date_added: "2024-01-06",
            type: "suits",
            collectionType: "silk",
          },
        ],
      },
    ],
  },
  {
    category: "jewellery",
    collections: [
      {
        slug: "necklaces-collection",
        heading: "Necklaces Collection",
        collectionType: "necklaces",
        type: "jewellery",
        images: ["/productImages/necklace1.jpg"],
        products: [
          {
            title: "Silver Necklace",
            images: [
              "/productImages/necklace1.jpg",
              "/productImages/necklace1-2.webp",
            ],
            slug: "silver-necklace",
            price: 1200,
            quantity: 25,
            description: "A traditional Silver necklace for festive occasions.",
            material: "Silver",
            washCare: "Wipe with a clean, dry cloth after use.",
            rating: 3.3,
            date_added: "2024-01-07",
            type: "jewellery",
            collectionType: "necklaces",
          },
        ],
      },
      {
        slug: "earrings-collection",
        heading: "Earrings Collection",
        collectionType: "earrings",
        type: "jewellery",
        images: ["/productImages/earring.webp"],
        products: [
          {
            title: "Gold Plated Earrings",
            images: ["/productImages/earring.webp"],
            slug: "gold-plated-earrings",
            price: 1000,
            quantity: 30,
            description: "A pair of traditional gold-plated earrings.",
            material: "Gold Plated Alloy",
            washCare: "Wipe with a clean, dry cloth after use.",
            rating: 3.4,
            date_added: "2024-01-08",
            type: "jewellery",
            collectionType: "earrings",
          },
        ],
      },
      {
        slug: "bangles-collection",
        heading: "Bangles Collection",
        collectionType: "bangles",
        type: "jewellery",
        images: ["/productImages/goldBangle.webp"],
        products: [
          {
            title: "Gold Plated Bangles",
            images: ["/productImages/goldBangle.webp"],
            slug: "gold-plated-bangles",
            price: 1500,
            quantity: 20,
            description: "A set of traditional gold-plated bangles.",
            material: "Gold Plated Alloy",
            washCare: "Wipe with a clean, dry cloth after use.",
            rating: 3.6,
            date_added: "2024-01-09",
            type: "jewellery",
            collectionType: "bangles",
          },
        ],
      },
    ],
  },
  {
    category: "shawls",
    collections: [
      {
        slug: "pashmina-shawl-collection",
        heading: "Pashmina Shawl Collection",
        collectionType: "pashmina",
        type: "shawls",
        images: ["/productImages/shawl1.webp"],
        products: [
          {
            title: "Pashmina Wool Shawl",
            images: [
              "/productImages/shawl1.webp",
              "/productImages/shawl1-1.webp",
            ],
            slug: "pashmina-wool-shawl",
            price: 3500,
            quantity: 7,
            description:
              "A warm and luxurious pashmina wool shawl, ideal for winters.",
            material: "Pashmina Wool",
            washCare: "Dry clean only.",
            rating: 5,
            date_added: "2024-01-10",
            type: "shawls",
            collectionType: "pashmina",
          },
        ],
      },
    ],
  },
];
